version: '3'
services:
  plantuml:
    image: 'plantuml/plantuml-server:latest'
    ports:
      - '8080:8080'
  postgres:
      image: postgres:14.2
      environment:
          - POSTGRES_USER=postgres_user
          - POSTGRES_PASSWORD=postgres_password
          - POSTGRES_DB=postgres_db
      ports:
          - '5432:5432'
