export function generateWarning(): string {
  return `/* --------------------------------------------------------------------- *\\
|  This code was auto-generated by the solidity-event-to-typeorm package. |
|                                                                         |
|  Changes to this file may cause incorrect behavior and will be lost if  |
|  the code is regenerated.                                               |
\\* ---------------------------------------------------------------------  */\n`;
}
